package com.banti.framework.resources;

import java.util.ListResourceBundle;

public class Resources extends ListResourceBundle {
	public Object[][] getContents() {
		return contents;
	}

	static final Object[][] contents = {
			{ "AQUA", "Aqua" },
			{ "ABOUT", "About.." },
			{ "ACCOUNT", "Account" },
			{ "ACCOUNT_MGMT", "Account Management" },
			{ "MSG_ACCOUNG_MGMT_UNAVAILABLE",
					"Only \"administrator\" can use the account management.." },
			{ "MSG_ACCOUNTS_LOAD_FAILED", "Unable to load accounts." },
			{ "ADD_ACCOUNT", "Create Account" },
			{ "ADD_TAB", "New Tab" },
			{ "ADD_TAB_TOOL_TIP", "Open a new tab" },
			{ "ALL_CLOSE", "Close All" },
			{ "APPLY", "Apply" },
			{ "BUILD", "Build" },
			{ "BUILD_VALUE", "sample build" },
			{ "CANCEL", "Cancel" },
			{ "CASCADE", "Cascade" },
			{ "CLOSE", "Close" },
			{ "CONFIRMATION", "Confirmation" },
			{ "CONNECT_TO", "Connected to" },
			{ "CONNECTING_TO", "Connecting to {SERVER}" },
			{ "CONTRAST", "Contrast" },
			{ "COPY", "Copy" },
			{ "CURRENT_PASSWD", "Old Password" },
			{ "CUT", "Cut" },
			{ "DEICONIFY", "Deiconify All" },
			{ "DELETE", "Delete" },
			{ "DELETE_ACCOUNT", "Delete Account" },
			{ "DELETE_ALL", "Clear All" },
			{ "DOMAIN", "Domain" },
			{ "CLEAR", "Clear" },
			{ "EDIT", "Edit" },
			{ "EMERALD", "Emerald" },
			{ "ENTRY", "Register" },
			{ "ERROR", "Error" },
			{ "EXIT", "Exit" },
			{ "EXIT_MESSAGE", "Do you wish to exit?" },
			{ "FILE", "File" },
			{ "GET_ROLE", "Get Role" },
			{ "HELP", "Help" },
			{ "HELP_CONTENTS", "Display Help" },
			{ "HELP_CONTENTS_TOOL_TIP", "Run a browser and show help contents" },
			{ "ICONIFY", "Iconify All" },
			{ "INFORMATION", "Information" },
			{ "LICENSE", "License" },
			{ "LICENSE_CODE", "License Code" },
			{ "LICENSE_ENTRY", "License Registration" },
			{ "LICENSE_TOOL_TIP", "Register and Confirm License Codes" },
			{ "LOGGED_IN", "Session Established" },
			{ "LOGIN", "Login" },
			{ "LOGOUT", "Logout" },
			{ "LOGOUT_FROM", " Disconnect from {SERVER}" },
			{ "LOOK_AND_FEEL", "Look & Feel" },
			{ "MAIN", " Main" },
			{ "MAIN_MAP_TITLE", "Main Map Window" },
			{ "MAP_UPLOAD", "Upload Map File" },
			{ "MAP_UPLOAD_TOOLTIP", "Upload Map File to Server" },
			{ "MAP_DISP_FILE", " Map File(.disp file)" },
			{ "MAXMIZE", "Maximize All" },
			{ "MENU", "Menu" },
			{ "MENU_BAR_TOOL_TIP", "Menu Bar" },
			{ "MENU_ITEM", "Menu Item" },
			{ "MSG_ACCESS_DENIED", " Access denied from {CLIENT}" },
			{ "MSG_ACCOUNT_DELETE_CONFIRMATION",
					"Do you really want to delete \"{ACCOUNT}\" ?" },
			{ "MSG_ACCOUNT_DELETED", "\"{ACCOUNT}\" was deleted successfully." },
			{ "MSG_ACCOUNT_ADDED", "\"{ACCOUNT}\" is created successfully." },
			{ "MSG_ACCOUNT_OVERLAP", "The account is already registered." },
			{ "MSG_ACCOUNT_RESERVED",
					"\"{ACCOUNT}\" is the reserved account.\nSo, it cannot be registered." },
			{ "MSG_ADD_FAILED", "Unable to add." },
			{ "MSG_CONNECT_ERROR", "Unable to connect to the server." },
			{ "MSG_SERVER_CONNECT_ERROR",
					"Unable to connect to the server \"{SERVER}\"." },
			{ "MSG_CONNECT_FAILED",
					"Unable to connect, Please check the Server." },
			{ "MSG_CONNECT_IO_ERROR",
					"Unable to communicate to the server because of Network Error." },
			{ "MSG_DELETE_FAILED", "Unable to delete." },
			{ "MSG_DO_LOGOUT", "Login session is closed." },
			{ "MSG_EXCLUSIVE_LOGIN",
					"{NAME} already login to the server from {CLIENT}." },
			{ "MSG_EXCLUSIVE_LOGIN2", "{NAME} already login to the server." },
			{ "MSG_GET_ROLE_SUCCESS", "Get Role Success" },
			{ "MSG_HELP_ERR", "Unable to open help contents." },
			{ "MSG_LAF_ERROR", "Unable to change the preference." },
			{ "MSG_LICENSE_DELETE_COMPLETED",
					"License Code was deleted completely." },
			{ "MSG_LICENSE_DELETE_CONFIRMATION", "Do you wish to delete?" },
			{ "MSG_LICENSE_INVALID", "Invalid License Code. Confirm again." },
			{ "MSG_LICENSE_VALID", "Product license registered successfully!" },
			{ "MSG_LICENSE_UNAVAILABLE",
					"Only \"administrator\" can enter license codes." },
			{ "MSG_LOGIN_SUCCESS", "Login successfully." },
			{ "MSG_SERVER_VERSION", "Server Version is {VERSION}." },
			{ "MSG_LOGIN_FAILED",
					"Unable to login. Please confirm Account and Password." },
			{ "MSG_LOGOUT_COMPLETED", "Logged out" },
			{ "MSG_LOGOUT_CONFIRMATION", "Logout?" },
			{ "MSG_MAPOPEN_FAILED", "Unable to open the map." },
			{ "MSG_MAPUPLOAD_SUCCESS",
					"The map file was uploaded successfully." },
			{ "MSG_MAPUPLOAD_FAILED", "The map file could not be uploaded." },
			{ "MSG_NOACCOUNT_ENTRY", "Account is mandatory." },
			{ "MSG_INVALID_ACCOUNT", "A comma is not used as your account." },
			{ "MSG_NONEWPASSWD_ENTRY", "New Password is mandatory." },
			{ "MSG_NOPASSWD_ENTRY", "Password is mandatory." },
			{ "MSG_NOREPASSWD_ENTRY", "Confirmation Password is mandatory." },
			{ "MSG_NOSERVER_ENTRY", "Enter an address to a server." },
			{ "MSG_NOT_LOGIN",
					"You are yet to login or session is lost. Please login again." },
			{ "MSG_NOTBOUND_EXCEPTION",
					"Server Lookup failure, server registry was not found." },
			{ "MSG_NOUSER_ENTRY", "Account is mandatory." },
			{ "MSG_ROLE", "UserRole:{ROLE}" },
			{ "MSG_ROLE_NULL", "UserRole:" },
			{ "MSG_PASSWD_CHANGED", "Password changed successfully." },
			{ "MSG_PASSWD_CHANGED_FAILED", "Password change failed." },
			{ "MSG_PASSWD_UNMATCH",
					"New password and confirm password does not match." },
			{ "MSG_SAMESERVER_ENTRY",
					"Already login to {SERVER}, Please enter again." },
			{ "MSG_SERVER_DOWN", "Server is down." },
			{ "MSG_SERVER_DOWN_FROM", "Server ({SERVER}),  is down." },
			{ "MSG_UNLOADED_CLASS_ERROR",
					"The request could not be transacted because of class loading error." },
			{ "MSG_UNMARSHAL_EXCEPTION",
					"Unable to communicate to the server because of compatibility problem." },
			{ "MSG_UNKNOWN_HOST", "The server was not found." },
			{ "MSG_UNSUPPORT_REQUEST", "Unsupported Request by the server." },
			{ "MSG_WRONG_PASSWD", "Old password is improper." },
			{ "NEW_PASSWD", "New Password" },
			{ "NO", "No" },
			{ "NO_LICENSE", "Need no License Code" },
			{ "OK", "OK" },
			{ "OPEN_MAP", "Open Map" },
			{ "OPEN_MAP_TOOLTIP", "Open a main map window" },
			{ "OPTION", "Options" },
			{ "OCEAN", "Ocean" },
			{ "PASSWD", "Password" },
			{ "PASSWD_REENTRY", "Confirm Password" },
			{ "PASSWORD_CHANGE", "Change Password" },
			{ "PASTE", "Paste" },
			{ "PLUGGED_MODULE", "Plug-in Module" },
			{ "PREFERENCE", "Preference" },
			{ "PREFERENCE_TOOL_TIP", "Configure Look & Feel" },
			{ "PREVIEW", "Print Preview" },
			{ "PRINT", "Print" },
			{ "PRINTING_ERROR", "Unable to print out." },
			{ "PRINT_SERVICE_NOT_FOUND",
					"An available print service was not found." },
			{ "REMOVE_TAB", "Close Tab" },
			{ "REMOVE_TAB_TOOL_TIP", "Close a current tab" },
			{ "ROLE", "Role" },
			{ "SANDSTONE", "Sand Stone" },
			{ "SELECT_ALL", "Select All" },
			{ "SELECT_MAP_FILE", "Select Map File (.disp file)" },
			{ "STATUS", "Status" },
			{ "STATUS_BAR_SWITCH", "Switch ON/OFF of Status Bar" },
			{ "STATUS_BAR_TOOL_TIP", "Status Bar" },
			{ "STEEL", "Steel" },
			{ "THEME", "Theme" },
			{ "TILE", "Tile" },
			{ "TOOL", "Tool" },
			{ "TOOL_BAR_SWITCH", "Switch ON/OFF of Tool Bar" },
			{ "TOOL_BAR_TOOL_TIP", "Tool Bar" },
			{ "VERSION", "Version" },
			{ "VERSION_VALUE", "1.0.0" },
			{ "VIEW", "View" },
			{ "WARNING", "Warning" },
			{ "WINDOW_BAR_SWITCH", "Switch ON/OFF of Window Bar" },
			{ "WINDOW_BAR_TOOL_TIP", "Window Bar" },
			{ "WINDOWS", "Window" },
			{ "YES", "Yes" },
			{ "MSG_UNABLE_SESSION_VALUE",
					"Unable to get session configuration value." },
			{ "SESSION_CONFIGURATION_DIALOG", "Session Configuration Dialog" },
			{ "AUTO_LOGOUT_MODE", "Auto Logout Mode" },
			{ "MSG_SESSION_CONFIGURATION",
					"Please set value for session configuration." },
			{ "TIMEOUT", "Timeout" },
			{ "TAG_HOUR", "hours" },
			{ "TAG_MIN", "min" },
			{ "MSG_SET_SESSION_VALUE_SUCCESS",
					"Succeeded to set session configuration value." },
			{ "MSG_SET_SESSION_VALUE_FAILED",
					"Failed to set session configuration value." },
			{ "SESSION_CONFIGURATION", "Session Configuration" },
			{ "MAP_DOWNLOAD", "Save Map file" },
			{ "MAP_DOWNLOAD_TOOLTIP",
					"Save Network map file to a specified folder." },
			{ "DOWNLOAD_SUCCEED", "Map file is saved successfully." },
			{ "DOWNLOAD_FAILED", "Failed to save map file." },
			{ "INVALID_FORMAT", "Operation log format is wrong" },
			{ "UNABLE_TO_READ", "Unable to read operation log file" },
			{ "NO_DATA", "Could not find data for the selected condition" },
			{ "OPERATION_LOG_SEARCH_STOPED", "Operation Log search stopped" },
			{ "ABORT_BUTTON", "Abort" },
			{ "CONNECT", "Connect to" },
			{ "CONNECTED_TO", "Connected to {SERVER}" },
			{ "ACCESS_DENIED", "Access Denied" },
			{ "LOGGEDIN_ACCOUNT_CANNOT_BE_DELETED",
					"Logged in account cannot be deleted" } };

}